version: '3'

services:
  api:
    build: .
    container_name: api
    ports:
      - "9999:5000"
    volumes:
      - ./examples:/shaclAPI/examples
      - ./output:/shaclAPI/output
    networks:
      - shacl_engine_tests

networks:
  shacl_engine_tests:
    driver: bridge
    external: true
